### ISSUE TITLE
Shadow Map - Py Error

### ISSUE THREAD

**Issue by madf0x** [rgsouthall/vi-suite07#1]
I've tried to run a shadow map calculation on the latest master using Blender 3.0.1 stable.

I assigned my light sensor material, set a location node and mapped it into the shadow map node.

As soon as I hit calculate I get the following error:

Python: Traceback (most recent call last):
  File "C:\Users\UserName\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\vi-suite07-master\vi_operators.py", line 495, in invoke
    for k in ovp.keys():
RuntimeError: IDPropertyGroup changed size during iteration

location: <unknown location>:-1

The popup with the progress stays at 0% and can be closed.

**Comment by rgsouthall** [comment]
Hi.
This has been fixed in master but v0.7 has not been released yet, and is still in development, so your mileage may vary.
