### ISSUE TITLE
Vi-Suite 0.7 not exporting some material definitions

### ISSUE THREAD

**Issue by mfloresVicomtech** [rgsouthall/vi-suite07#10]
Hi again,

It looks like the latest version of Vi-Suite is not exporting "Internal floor 1" & "Party Wall 1" specs to IDF, as it returns this error on EnVi Simulation calculation:

> Program Version,EnergyPlus, Version 22.1.0-ed759b17ee, YMD=2023.11.29 12:24,
>    ** Severe  ** Did not find matching material for Construction FLOOR, missing material = FLOOR-LAYER-0
>    ** Severe  ** Did not find matching material for Construction FLOOR, missing material = FLOOR-LAYER-1
>    ** Severe  ** Did not find matching material for Construction FLOOR, missing material = FLOOR-LAYER-2
>    ** Severe  ** Did not find matching material for Construction INTERNAL_WALLS, missing material = INTERNAL_WALLS-LAYER-0
>    ** Severe  ** Did not find matching material for Construction INTERNAL_WALLS, missing material = INTERNAL_WALLS-LAYER-1
>    ** Severe  ** Did not find matching material for Construction INTERNAL_WALLS, missing material = INTERNAL_WALLS-LAYER-2
>    ** Severe  ** Nominal U is zero, for construction=FLOOR
>    ** Severe  ** Nominal U is zero, for construction=INTERNAL_WALLS

Checking the exported IDF, "Construction" for that EnVi material is created, but not the "Material" definition for each layer.

Find attached the blend file for you to test.
[visuite0.7_testing.zip](https://github.com/rgsouthall/vi-suite07/files/13500035/visuite0.7_testing.zip)

**Comment by rgsouthall** [comment]
Thanks for the bug report. Keep 'em comin'.
This should now be fixed in master.
P.S. Nice to see someone keep their VI-Suite nodes in such tidy order.

**Comment by rgsouthall** [comment]
As there has been no further reports I assume I can close this.
