### ISSUE TITLE
Annual glare study - An error code

### ISSUE THREAD

**Issue by olemariussvendsen** [rgsouthall/vi-suite07#12]
Good morning Ryan, i finaly had time to test out the annual glare simulation with Blender 4.

As i understand how to set it up, it should be somewhat like this:

![2023-12-04_08-32-58](https://github.com/rgsouthall/vi-suite07/assets/135004477/02051a39-8563-49dd-892b-ba6d7a86b8af)

A side note, it does not seem it can be multi tread calculation, is that correct? If so, the modul might not be easy to use as it took me 1 hour to run the simulation.

Anyhow, when trying to push activate glare in the "LiVi Glare" following error code comes:

Python: Traceback (most recent call last):
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\vi-suite07-master\vi_operators.py", line 1738, in execute
    imy = int(line.decode().split(' ')[1])
ValueError: invalid literal for int() with base 10: ''

**Comment by rgsouthall** [comment]
No, you don't use it like that. That is an instantaneous glare analysis set up. 
You plug the LiVi Geometry and LiVi Context nodes into a LiVi Simulation node. Once the simulation is done you display results with the VI display panel.

This is an initial implementation. Multi-threading is tricky, and you will need to have a little patience I'm afraid.

**Comment by olemariussvendsen** [comment]
Deepest apologize to not have used it correctly. I did as you instructed and i do get results in 3D view + as a CSV results. Will play around with the different views and thresholds to beter learn it. I think we should close this as you have instructed other to use the google forum for assistance, it was my missunderstanding and therfor no bug has been found.
