### ISSUE TITLE
Reference to PyQt6 in vi_display.py

### ISSUE THREAD

**Issue by ger08061959** [rgsouthall/vi-suite07#14]
In vi_display.py there is an import from PyQt6. Won't be an issue with PyQt6 installed but most installs and modules are still on Qt5. Replaced with PySide2 and Blender will load.

**Comment by rgsouthall** [comment]
Hi. Thanks for the report. PyQt6 got removed a while ago from master in favour of PySide6. I can find no reference to PyQt6 in vi_display.py in current master. Are you using an older branch?

**Comment by ger08061959** [comment]
No, I was using the latest branch, I will try it with a newer download with
Blender 4.0, 3.6.7 and 3.3
Tried several configs but that gave an error that it couldn't load
PyQt6.QtCore, Complains (on windows 11) it is missing a Python3.dll and on
linux (Ubuntu 22.04). It just can't find QtCore.

I will try with PySide6 installed, but I haven't tested that yet.

**Comment by ger08061959** [comment]
Became running again after reinstallation of Blender 4, cleanup and removal of sverchok:
![Schermafbeelding 2024-01-12 144132](https://github.com/rgsouthall/vi-suite07/assets/5363443/11c0587b-ade9-4bce-b8d2-d38ad979679d)
![Schermafbeelding 2024-01-12 142557](https://github.com/rgsouthall/vi-suite07/assets/5363443/319fe9e9-afdd-4b06-b1e1-23ad07d340dd)

Thanks for hint, I will put pyside6 and see if sverchok/vi-suite will work with both enabled.

**Comment by rgsouthall** [comment]
Glad you got it working. I'll close this now.
If the VI-Suite does not find PySide6 it will try and install it itself via pip.
