### ISSUE TITLE
VI-Suite Object Definition not showing up

### ISSUE THREAD

**Issue by MechanicalMagnificus** [rgsouthall/vi-suite07#16]
I’ve successfully done simple renders with Radiance using Vi-Suite version 0.7, but “VI-Suite Object Definition” is not showing up, but other features, like LiVi nodes, are. I tried uninstalling and reinstalling Vi-Suite per the user manual. Can you please tell me what might be wrong?

I’m on windows 64 bit, blender 4.0, Vi-suite 0.7, and Radiance 6.0a.

**Comment by rgsouthall** [comment]
At the moment this sounds like a usage issue rather than a code issue so the Google group https://groups.google.com/g/vi-suite is a better place for this.
