### ISSUE TITLE
Run error VI-Node - several code errors, might be UTF-8 encode

### ISSUE THREAD

**Issue by olemariussvendsen** [rgsouthall/vi-suite07#17]
Edit:
- Important selv criticism on my behalf. I forgot to add grids to the faces i wanted to have the simulation run by. So some of the error code might be gone now, though i still can not run the simulation.

"Writen before added the surface grid":

Evening Ryan, i hope you are doing well. All fine here, have started implementing VI-Suite far more, and the intrest for its capability is growing within our workspace. However, when i am trying to set up yet another annual Glare study, i do get this error code for this spesific project: when exporting the Livi Context node (file in the end of this bug report:

I have tried my very best to make sure the "/" is removed as i have several sucsesful runs now with other projects. Also i have removed all norwegian letters i could find "øØ. æÆ and åÅ. Only one i could not remove is the path which has the word "Arbeidsområde".

C:\OneDrive\Marini Consulting AS\Prosjekter - General\23083 Grensen 3\3_Arbeidsområde\3_1_Arbeidsdokumenter\Simuleringer\Blending

Error code:

```
Python: Traceback (most recent call last):
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\vi-suite07-master\vi_node.py", line 762, in export
    self['Options']['MTX'] = mtxfile.read()
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 114: invalid continuation byte
```

When i push export from Livi Geometry Node i get the following code:

`The directory path or Blender filename has non-ascii characters in it. Photon mapping may not work
`
However, when i copy the entire folder from our company onedrive (with the Å letter in Arbeidsområde), into a my personal download folder neither error codes shows up. Though i still can not run the simulation

Also when having my file in the OneDrive folder, the livi SImulation node goes from non active for simulation accuracy to beeing allowed to select an accuracy. However i can still not seem to run any simulation. 

![image](https://github.com/rgsouthall/vi-suite07/assets/135004477/7dcd5a00-24fd-414b-a8c6-c2f7281d2217)

File i am using:
https://we.tl/t-yVTByt5vVk

**Comment by olemariussvendsen** [comment]
Edit:
- Important selv criticism on my behalf. I forgot to add grids to the faces i wanted to have the simulation run by. So some of the error code might be gone now, though i still can not run the simulation.

**Comment by rgsouthall** [comment]
It seems it doesn't like the sky matrix, which is based on the EPW file, so you may have to check the EPW file for funny characters. Your we transfer link doesn't seem to work for me.

**Comment by olemariussvendsen** [comment]
I have tried several EPW files from different European location, non of them seem to work for this spesific file.

I have made a new We Transfare:
https://we.tl/t-vs0cojKrVG

**Comment by olemariussvendsen** [comment]
I think i have found out on my own the issue. Testing the file now.

Seems like i have been a bit to hasty to set up the calculation model. I have forgoten to set the sensor as the right material.

![image](https://github.com/rgsouthall/vi-suite07/assets/135004477/37a7bfcd-ce01-4d44-87ac-2fc835aacadd)

However, it still seems like when trying to run the file in a folder with non english letter, it yields a problem where the file won't run. Would this in itself be possible to add something for Blenders python raspatory to avoid?

**Comment by olemariussvendsen** [comment]
Happy to announce it was the self caused issue described above that caused the error.  i Am closing this as it was not a bug, beside trying to run the file in a non english letter folder.

**Comment by rgsouthall** [comment]
The VI Location node now returns a Non-ascii menu entry when it finds a non-ascii character in the EPW file path. 
The LiVi Simulation node now says if there are no calculation surfaces.

**Comment by rgsouthall** [comment]
Or at least they will do when I next commit to master

**Comment by olemariussvendsen** [comment]
Thank you for your reply. After more testing, it seems like objects and meshes, even materials with non-ascii character will still run the simulation. It seems for me as long as the file is in a folder with a non-ascii is when the problem occur. Would the potential bug fix still allow the file to run as long as the non-ascii only applies for object, mesh and materials? Would be a lot of editing to take these outs, appose as just changing the folder destination.
