### ISSUE TITLE
Is there some updated Documentation?

### ISSUE THREAD

**Issue by Sinasta** [rgsouthall/vi-suite07#3]
Hey Ryan, i am considering using Vi-suite for my master thesis and i would like to know if there are some up-to-date tutorials/documentation/manuals on how to do energy analysis? Thank's a lot for this great Add-On!

**Comment by rgsouthall** [comment]
Not yet. Energy analysis is pretty similar to the previous versions though and has the same capabilities. May be more documentation over the summer depending on the frequency of beach weather. Google group is better for questions such as this. Here is more for bug reports.

**Comment by Sinasta** [comment]
Thanks a lot for your answer, would be lovely if you could spare the time for some documentation. Thank you for your work!
