### ISSUE TITLE
Run on Apple Silicon M1

### ISSUE THREAD

**Issue by yanxiang-wang** [rgsouthall/vi-suite07#5]
Hi, 
Is this add-on compatible with the Apple M1 chip? Or it requires the x86 architecture. Thanks.

**Comment by rgsouthall** [comment]
I don't have access to m1 hardware so cannot be sure, but a user has reported that they have got it working on m1. If you put a message on https://groups.google.com/g/vi-suite they may be able to help with the specifics.

**Comment by yanxiang-wang** [comment]
Thanks for your information. @rgsouthall
